# Configuración simplificada de Netlify

# Redirecciones para la API
[[redirects]]
  from = "/api/*"
  to = "https://mipaginaprueba.rf.gd/api/:splat"
  status = 200
  force = true

# Asegura que la SPA funcione correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
